# Generated by Django 2.0.13 on 2019-04-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='published_date',
        ),
    ]
